---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: ansible
name: microsoft.mecm
version: 0.1.0
readme: README.md
authors:
  - Ansible Community
description: Ansible collection for managing Microsoft System Center Configuration Manager (MECM/SCCM/ConfigMgr)
license_file: LICENSE
tags:
  - microsoft
  - mecm
  - sccm
  - configmgr
  - windows
  - infrastructure
repository: https://github.com/ansible-collections/microsoft.mecm
# documentation: https://github.com/ansible-collections/microsoft.mecm/tree/main/docs
homepage: https://github.com/ansible-collections/microsoft.mecm
issues: https://github.com/ansible-collections/microsoft.mecm/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
